[project]
name = "PySide QtQuick Project"

[tool.pyside6-project]
files = ["main.py", "main.qml", "Components/Canvas.qml", "Components/StatusBar.qml", "Components/ToolBar.qml", "Components/MenuBar.qml"]
